name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'    # æ¯å¤© 00:00 è‡ªåŠ¨æ›´æ–°
  workflow_dispatch:       # æ‰‹åŠ¨è§¦å‘ä¹Ÿå¯ä»¥

jobs:
  update-waka-stats:
    runs-on: ubuntu-latest
    
    # ğŸŒŸ å…³é”®ä¿®æ”¹ï¼šåŠ ä¸Š environment å­—æ®µï¼ŒæŒ‡å®š Secret æ‰€åœ¨çš„ç¯å¢ƒ
    # åªæœ‰æŒ‡å®šäº†è¿™ä¸ªç¯å¢ƒï¼ŒJob æ‰èƒ½è®¿é—®åˆ°ç¯å¢ƒ Secrets (GH_TOKEN å’Œ WAKATIME_API_KEY)
    environment: WakaTimeè‡ªåŠ¨æ›´æ–°
    # ğŸŒŸ å…³é”®ä¿®æ­£ï¼šæ·»åŠ  Job æƒé™é…ç½®
    permissions:
      contents: write
      traffic: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_TIMEZONE: true
          SHOW_COMMIT: true
          SHOW_LANGUAGE: true
          SHOW_LINES_OF_CODE: false
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LOC_CHART: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_PROFILE_VIEWS: true
          SHOW_SHORT_INFO: true
          SHOW_UPDATED_DATE: true
          SHOW_TOTAL_CODE_TIME: true
          COMMIT_BY_ME: false
          COMMIT_MESSAGE: Updated with Dev Metrics
          COMMIT_SINGLE: false
          LOCALE: en
          UPDATED_DATE_FORMAT: '%d/%m/%Y %H:%M:%S'
          SYMBOL_VERSION: 1