name: WakaTime Dev Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest
    
    env:
      TZ: Asia/Shanghai # ç¡®ä¿ Runner ç³»ç»Ÿæ—¶é—´ä¸ºåŒ—äº¬æ—¶é—´
      
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run WakaTime Stats Action
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          SECTION_NAME: waka
          # ğŸ”’ éšç§ä¸èŒƒå›´è®¾ç½®
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_OS: false
          SHOW_EDITORS: true
          
          # ğŸš€ æ•°æ®å±•ç¤ºè®¾ç½®
          SHOW_LINES_OF_CODE: true
          SHOW_LOC_CHART: true
          SHOW_COMMIT: true
          SHOW_LANGUAGE: true
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_PROFILE_VIEWS: true
          
          # ğŸ’¡ è¿™é‡Œå»ºè®®è®¾ä¸º trueï¼Œå®ƒä¼šæ˜¾ç¤ºâ€œLast 7 daysâ€å­—æ ·å’Œå…·ä½“æ—¥æœŸèŒƒå›´
          SHOW_SHORT_INFO: true
          
          SHOW_UPDATED_DATE: true
          SHOW_TOTAL_CODE_TIME: true
          
          # ğŸ¨ æ ¼å¼åŒ–è®¾ç½®
          COMMIT_MESSAGE: "Updated with Dev Metrics ğŸ®"
          LOCALE: zh
          # è¿™æ ·å†™é…åˆ TZ ç¯å¢ƒå˜é‡ï¼Œè¾“å‡ºçš„å°±æ˜¯çº¯æ­£çš„åŒ—äº¬æ—¶é—´å•¦ï¼
          UPDATED_DATE_FORMAT: '%Y/%m/%d %H:%M:%S'
          UPDATED_DATE_TEXT: "æœ€åæ›´æ–°äº"
          SYMBOL_VERSION: 1